# Generated by Django 2.0.7 on 2018-09-08 06:35

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HintNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('index_in_contract', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestForFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=130)),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('photo', models.ImageField(upload_to=core.models.images_upload_to)),
                ('description', models.TextField(max_length=1024)),
                ('creator_address', models.CharField(max_length=300)),
                ('creator_email', models.EmailField(max_length=254)),
                ('contract_deployed_address', models.CharField(max_length=300)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Requests for finds',
                'verbose_name': 'Request for find',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='hintnotification',
            name='find_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.RequestForFind'),
        ),
    ]
