# Generated by Django 2.0.7 on 2018-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforfind',
            name='location',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestforfind',
            name='lost_date',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
