# Generated by Django 2.0.7 on 2018-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180908_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_address', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'system settings',
                'verbose_name': 'system settings',
            },
        ),
    ]
