# Generated by Django 2.0.7 on 2018-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforfind',
            name='contract_status',
            field=models.IntegerField(default=1),
        ),
    ]
